/* Generated By:JavaCC: Do not edit this line. SubLParserConstants.java */
package com.cyc.tool.subl.parser;

public interface SubLParserConstants {

  int EOF = 0;
  int OPEN_PAREN = 1;
  int CLOSE_PAREN = 2;
  int PACKAGE_SEPARATOR = 3;
  int SUBL_SYMBOL_NAME_QUOTE = 4;
  int VECTOR_PREFIX = 5;
  int FUNCTION_QUOTE = 6;
  int QUOTE_CHAR = 7;
  int BACK_QUOTE = 8;
  int SPLICING_UNQUOTE = 9;
  int UNQUOTE = 10;
  int DOT = 11;
  int STRING_QUOTE = 12;
  int UNINTERNED_SYMBOL_PREFIX = 13;
  int READ_TIME_EVALUATION = 14;
  int IF_FEATURE = 15;
  int IF_NOT_FEATURE = 16;
  int CHARACTER_PREFIX = 17;
  int HASH_MARK = 18;
  int BACKSLASH = 19;
  int SINGLE_LINE_COMMENT = 22;
  int MULTI_LINE_COMMENT = 23;
  int WS = 25;
  int FLOAT1 = 26;
  int FLOAT2 = 27;
  int EXPONENT = 28;
  int DECIMAL_INTEGER = 29;
  int BASED_INTEGER = 30;
  int BASED_INTEGER_PREFIX = 31;
  int NUMBER_CHAR = 32;
  int NAMED_CHARACTER = 33;
  int CHARACTER = 34;
  int CHARACTER_START = 35;
  int CONTROL_BITS = 36;
  int CONTROL_LONG = 37;
  int CONTROL_SHORT = 38;
  int META_LONG = 39;
  int META_SHORT = 40;
  int CHAR_NAME = 41;
  int STRING = 42;
  int CASE_SENSITIVE_SUBL_SYMBOL_NAME = 43;
  int CONSTITUENT_CHAR = 44;
  int PRINTABLE_CHAR = 45;
  int SUBL_SYMBOL_NAME = 46;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"|\"",
    "\"#(\"",
    "\"#\\\'\"",
    "\"\\\'\"",
    "\"`\"",
    "\",@\"",
    "\",\"",
    "\".\"",
    "\"\\\"\"",
    "\"#:\"",
    "\"#.\"",
    "\"#+\"",
    "\"#-\"",
    "\"#\\\\\"",
    "\"#\"",
    "\"\\\\\"",
    "\";\"",
    "\"#|\"",
    "<SINGLE_LINE_COMMENT>",
    "\"|#\"",
    "<token of kind 24>",
    "<WS>",
    "<FLOAT1>",
    "<FLOAT2>",
    "<EXPONENT>",
    "<DECIMAL_INTEGER>",
    "<BASED_INTEGER>",
    "<BASED_INTEGER_PREFIX>",
    "<NUMBER_CHAR>",
    "<NAMED_CHARACTER>",
    "<CHARACTER>",
    "<CHARACTER_START>",
    "<CONTROL_BITS>",
    "\"Control-\"",
    "\"C-\"",
    "\"Meta-\"",
    "\"M-\"",
    "<CHAR_NAME>",
    "<STRING>",
    "<CASE_SENSITIVE_SUBL_SYMBOL_NAME>",
    "<CONSTITUENT_CHAR>",
    "<PRINTABLE_CHAR>",
    "<SUBL_SYMBOL_NAME>",
  };

}
