#**********************************************************
# Build the .beam erlang VM files
# Makefile for irc bot (based on manderlbrot)
# Based on manderlbot - 0.9.2
#**********************************************************

VERSION     = 0.0.1

all: clean

clean:
	-rm -f *.fasl

