/***
 *   Copyright (c) 1995-2009 Cycorp Inc.
 * 
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *   
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 *  Substantial portions of this code were developed by the Cyc project
 *  and by Cycorp Inc, whose contribution is gratefully acknowledged.
*/

package  com.cyc.cycjava.cycl;

import com.cyc.tool.subl.util.SubLFile;
import com.cyc.tool.subl.util.SubLFiles;

public class cycl implements SubLFile {
  
  //// Constructors
  
  /** Creates a new instance of cycl. */
  public cycl() {}
  
  public static final SubLFile me = new cycl();
  
  //// Initializers
  
  public void declareFunctions() {
  }
  
  public void initializeVariables() {
  }
  
  public void runTopLevelForms() {
    //SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_cvs_id");
    SubLFiles.initialize("com.cyc.cycjava.cycl.meta_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.access_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.subl_macro_promotions");
    SubLFiles.initialize("com.cyc.cycjava.cycl.subl_promotions");
    SubLFiles.initialize("com.cyc.cycjava.cycl.subl_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.format_nil");
    SubLFiles.initialize("com.cyc.cycjava.cycl.modules");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_revision_extraction");
    SubLFiles.initialize("com.cyc.cycjava.cycl.system_parameters");
    SubLFiles.initialize("com.cyc.cycjava.cycl.system_version");
    SubLFiles.initialize("com.cyc.cycjava.cycl.system_info");
    SubLFiles.initialize("com.cyc.cycjava.cycl.utilities_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.timing");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_file_dependencies");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.cycml_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.control_vars");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.sunit_macros");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.sunit_external");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cfasl");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.sxhash_external");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.red_implementation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.red_api");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.cyc_testing_initialization");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.cyc_testing");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.generic_testing");
    SubLFiles.initialize("com.cyc.cycjava.cycl.hash_table_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.keyhash");
    SubLFiles.initialize("com.cyc.cycjava.cycl.set_contents");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.reader_writer_locks");
    SubLFiles.initialize("com.cyc.cycjava.cycl.memoization_state");
    SubLFiles.initialize("com.cyc.cycjava.cycl.list_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.transform_list_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.vector_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.string_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.unicode_strings");
    SubLFiles.initialize("com.cyc.cycjava.cycl.unicode_subsets");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.unicode_support");
    SubLFiles.initialize("com.cyc.cycjava.cycl.unicode_streams");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.defstruct_sequence");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.visitation_utilities");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.mail_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.mail_message");
    SubLFiles.initialize("com.cyc.cycjava.cycl.number_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.fraction_utilities");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.matrix_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.numeric_date_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.iteration");
    SubLFiles.initialize("com.cyc.cycjava.cycl.binary_tree");
    SubLFiles.initialize("com.cyc.cycjava.cycl.stacks");
    SubLFiles.initialize("com.cyc.cycjava.cycl.queues");
    SubLFiles.initialize("com.cyc.cycjava.cycl.deck");
    SubLFiles.initialize("com.cyc.cycjava.cycl.integer_sequence_generator");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.semaphores");
    SubLFiles.initialize("com.cyc.cycjava.cycl.process_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.os_process_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.tcp_server_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.pattern_match");
    SubLFiles.initialize("com.cyc.cycjava.cycl.tries");
    SubLFiles.initialize("com.cyc.cycjava.cycl.shelfs");
    SubLFiles.initialize("com.cyc.cycjava.cycl.id_index");
    SubLFiles.initialize("com.cyc.cycjava.cycl.dictionary_contents");
    SubLFiles.initialize("com.cyc.cycjava.cycl.dictionary");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cfasl_compression");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cfasl_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.bijection");
    SubLFiles.initialize("com.cyc.cycjava.cycl.glob");
    SubLFiles.initialize("com.cyc.cycjava.cycl.keyhash_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.set");
    SubLFiles.initialize("com.cyc.cycjava.cycl.set_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.dictionary_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.map_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.bag");
    SubLFiles.initialize("com.cyc.cycjava.cycl.accumulation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.red_infrastructure");
    SubLFiles.initialize("com.cyc.cycjava.cycl.red_infrastructure_macros");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.red_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.file_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.stream_buffer");
    SubLFiles.initialize("com.cyc.cycjava.cycl.hierarchical_visitor");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.strie");
    SubLFiles.initialize("com.cyc.cycjava.cycl.finite_state_transducer");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cache");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cache_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.special_variable_state");
    SubLFiles.initialize("com.cyc.cycjava.cycl.simple_lru_cache_strategy");
    SubLFiles.initialize("com.cyc.cycjava.cycl.file_hash_table");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.file_hash_table_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.file_vector");
    SubLFiles.initialize("com.cyc.cycjava.cycl.file_vector_utilities");
 //   SubLFiles.initialize("com.cyc.cycjava.cycl.generic_table_utilities");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.sdbc_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sdbc");
    SubLFiles.initialize("com.cyc.cycjava.cycl.graph_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sparse_vector");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sparse_matrix");
    SubLFiles.initialize("com.cyc.cycjava.cycl.remote_image");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.cyc_testing_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.heap");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.decision_tree");
    SubLFiles.initialize("com.cyc.cycjava.cycl.misc_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.web_utilities");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.timing_by_category");
    SubLFiles.initialize("com.cyc.cycjava.cycl.api_control_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.eval_in_api");
    SubLFiles.initialize("com.cyc.cycjava.cycl.eval_in_api_registrations");
    SubLFiles.initialize("com.cyc.cycjava.cycl.api_kernel");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cfasl_kernel");
    SubLFiles.initialize("com.cyc.cycjava.cycl.guardian");
    SubLFiles.initialize("com.cyc.cycjava.cycl.hl_interface_infrastructure");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.constant_completion_low");
    SubLFiles.initialize("com.cyc.cycjava.cycl.constant_completion_interface");
    SubLFiles.initialize("com.cyc.cycjava.cycl.constant_completion_high");
    SubLFiles.initialize("com.cyc.cycjava.cycl.constant_completion");
    SubLFiles.initialize("com.cyc.cycjava.cycl.constant_handles");
    SubLFiles.initialize("com.cyc.cycjava.cycl.constant_reader");
    SubLFiles.initialize("com.cyc.cycjava.cycl.enumeration_types");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_control_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.mt_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.graphl_search_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.ghl_search_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_iteration");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_paranoia");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_module_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_link_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_marking_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_search_datastructures");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_search_vars");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_time_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_link_iterators");
    SubLFiles.initialize("com.cyc.cycjava.cycl.at_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.gt_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.czer_vars");
    SubLFiles.initialize("com.cyc.cycjava.cycl.mt_relevance_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.pred_relevance_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.at_macros");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.czer_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.wff_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.wff_vars");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.gt_macros");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.hl_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.obsolete");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.obsolete_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_mapping_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_access_metering");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_object_manager");
    SubLFiles.initialize("com.cyc.cycjava.cycl.hlmt");
    SubLFiles.initialize("com.cyc.cycjava.cycl.hlmt_czer");
    SubLFiles.initialize("com.cyc.cycjava.cycl.constants_interface");
    SubLFiles.initialize("com.cyc.cycjava.cycl.constant_index_manager");
    SubLFiles.initialize("com.cyc.cycjava.cycl.constants_low");
    SubLFiles.initialize("com.cyc.cycjava.cycl.constants_high");
    SubLFiles.initialize("com.cyc.cycjava.cycl.nart_handles");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.narts_interface");
    SubLFiles.initialize("com.cyc.cycjava.cycl.nart_index_manager");
    SubLFiles.initialize("com.cyc.cycjava.cycl.nart_hl_formula_manager");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.narts_low");
    SubLFiles.initialize("com.cyc.cycjava.cycl.narts_high");
    SubLFiles.initialize("com.cyc.cycjava.cycl.forts");
    SubLFiles.initialize("com.cyc.cycjava.cycl.assertion_handles");
    SubLFiles.initialize("com.cyc.cycjava.cycl.assertions_interface");
    SubLFiles.initialize("com.cyc.cycjava.cycl.assertion_manager");
    SubLFiles.initialize("com.cyc.cycjava.cycl.assertions_low");
    SubLFiles.initialize("com.cyc.cycjava.cycl.assertions_high");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_hl_support_manager");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_hl_supports");
    SubLFiles.initialize("com.cyc.cycjava.cycl.deduction_handles");
    SubLFiles.initialize("com.cyc.cycjava.cycl.deductions_interface");
    SubLFiles.initialize("com.cyc.cycjava.cycl.deduction_manager");
    SubLFiles.initialize("com.cyc.cycjava.cycl.deductions_low");
    SubLFiles.initialize("com.cyc.cycjava.cycl.deductions_high");
    SubLFiles.initialize("com.cyc.cycjava.cycl.unrepresented_term_index_manager");
    SubLFiles.initialize("com.cyc.cycjava.cycl.unrepresented_terms");
    SubLFiles.initialize("com.cyc.cycjava.cycl.arguments");
    SubLFiles.initialize("com.cyc.cycjava.cycl.clause_strucs");
    SubLFiles.initialize("com.cyc.cycjava.cycl.variables");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.format_cycl_expression");
    SubLFiles.initialize("com.cyc.cycjava.cycl.hl_storage_modules");
    SubLFiles.initialize("com.cyc.cycjava.cycl.hl_modifiers");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.sxhash_external_kb");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.el_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cycl_variables");
    SubLFiles.initialize("com.cyc.cycjava.cycl.el_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.clause_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cycl_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cycl_grammar");
    SubLFiles.initialize("com.cyc.cycjava.cycl.el_grammar");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.unicode_nauts");
    SubLFiles.initialize("com.cyc.cycjava.cycl.term");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_indexing_datastructures");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.simple_indexing");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_indexing_declarations");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_indexing_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_indexing");
    SubLFiles.initialize("com.cyc.cycjava.cycl.virtual_indexing");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_mapping");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_mapping_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_gp_mapping");
    SubLFiles.initialize("com.cyc.cycjava.cycl.somewhere_cache");
    SubLFiles.initialize("com.cyc.cycjava.cycl.auxiliary_indexing");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inferred_indexing");
    SubLFiles.initialize("com.cyc.cycjava.cycl.arity");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_accessors");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.kb_iterators");
    SubLFiles.initialize("com.cyc.cycjava.cycl.function_terms");
    SubLFiles.initialize("com.cyc.cycjava.cycl.relation_evaluation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.assertion_utilities");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.parameter_specification_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.clauses");
    SubLFiles.initialize("com.cyc.cycjava.cycl.bindings");
    SubLFiles.initialize("com.cyc.cycjava.cycl.unification");
    SubLFiles.initialize("com.cyc.cycjava.cycl.unification_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.file_backed_cache");
    SubLFiles.initialize("com.cyc.cycjava.cycl.graphl_graph_utilities");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.ghl_graph_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.ghl_link_iterators");
    SubLFiles.initialize("com.cyc.cycjava.cycl.ghl_marking_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.ghl_search_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_graphs");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_caching_policies");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_module_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_links");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_nat_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_link_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_link_methods");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_marking_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_search_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_marking_methods");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_search_methods");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_search_what_mts");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_search_implied_relations");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_module_declarations");
    SubLFiles.initialize("com.cyc.cycjava.cycl.genls");
    SubLFiles.initialize("com.cyc.cycjava.cycl.disjoint_with");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sdc");
    SubLFiles.initialize("com.cyc.cycjava.cycl.isa");
    SubLFiles.initialize("com.cyc.cycjava.cycl.genl_predicates");
    SubLFiles.initialize("com.cyc.cycjava.cycl.negation_predicate");
    SubLFiles.initialize("com.cyc.cycjava.cycl.genl_mts");
    SubLFiles.initialize("com.cyc.cycjava.cycl.mt_relevance_cache");
    SubLFiles.initialize("com.cyc.cycjava.cycl.predicate_relevance_cache");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.negation_mt");
    SubLFiles.initialize("com.cyc.cycjava.cycl.ghl_search_methods");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sbhl.sbhl_cache");
    SubLFiles.initialize("com.cyc.cycjava.cycl.fort_types_interface");
    SubLFiles.initialize("com.cyc.cycjava.cycl.czer_trampolines");
    SubLFiles.initialize("com.cyc.cycjava.cycl.wff_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.wff_module_datastructures");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.wff_modules");
    SubLFiles.initialize("com.cyc.cycjava.cycl.wff");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.wff_suggest");
    SubLFiles.initialize("com.cyc.cycjava.cycl.simplifier");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.tersifier");
    SubLFiles.initialize("com.cyc.cycjava.cycl.verbosifier");
    SubLFiles.initialize("com.cyc.cycjava.cycl.czer_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.precanonicalizer");
    SubLFiles.initialize("com.cyc.cycjava.cycl.postcanonicalizer");
    SubLFiles.initialize("com.cyc.cycjava.cycl.clausifier");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.prop_sentence_clausifier");
    SubLFiles.initialize("com.cyc.cycjava.cycl.czer_graph");
    SubLFiles.initialize("com.cyc.cycjava.cycl.czer_main");
    SubLFiles.initialize("com.cyc.cycjava.cycl.rule_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.skolems");
    SubLFiles.initialize("com.cyc.cycjava.cycl.czer_meta");
    SubLFiles.initialize("com.cyc.cycjava.cycl.uncanonicalizer");
    SubLFiles.initialize("com.cyc.cycjava.cycl.canon_tl");
    SubLFiles.initialize("com.cyc.cycjava.cycl.at_routines");
    SubLFiles.initialize("com.cyc.cycjava.cycl.at_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.at_admitted");
    SubLFiles.initialize("com.cyc.cycjava.cycl.at_defns");
    SubLFiles.initialize("com.cyc.cycjava.cycl.defns");
    SubLFiles.initialize("com.cyc.cycjava.cycl.at_var_types");
    SubLFiles.initialize("com.cyc.cycjava.cycl.at_cache");
    SubLFiles.initialize("com.cyc.cycjava.cycl.arg_type");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.applicable_relations");
    SubLFiles.initialize("com.cyc.cycjava.cycl.sksi.sksi_infrastructure.sksi_macros");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.janus_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.gt_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.gt_search");
    SubLFiles.initialize("com.cyc.cycjava.cycl.gt_methods");
    SubLFiles.initialize("com.cyc.cycjava.cycl.transitivity");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.transfers_through");
    SubLFiles.initialize("com.cyc.cycjava.cycl.tva_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.tva_tactic");
    SubLFiles.initialize("com.cyc.cycjava.cycl.tva_strategy");
    SubLFiles.initialize("com.cyc.cycjava.cycl.tva_inference");
    SubLFiles.initialize("com.cyc.cycjava.cycl.tva_cache");
    SubLFiles.initialize("com.cyc.cycjava.cycl.equality_store");
    SubLFiles.initialize("com.cyc.cycjava.cycl.equals");
    SubLFiles.initialize("com.cyc.cycjava.cycl.rewrite_of_propagation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.hl_supports");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.conflicts");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.ebl");
    SubLFiles.initialize("com.cyc.cycjava.cycl.preserves_genls_in_arg");
    SubLFiles.initialize("com.cyc.cycjava.cycl.formula_pattern_match");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cfasl_kb_methods");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_modules");
    SubLFiles.initialize("com.cyc.cycjava.cycl.search");
    SubLFiles.initialize("com.cyc.cycjava.cycl.tms");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.after_adding");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.rule_after_adding");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.after_adding_modules");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.argumentation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.backward");
    SubLFiles.initialize("com.cyc.cycjava.cycl.psc");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.inference_trampolines");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.inference_completeness_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.backward_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.backward_results");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.transformation_heuristics");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.inference_pad_data");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.preference_modules");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.preference_module_declarations");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_datastructures_enumerated_types");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_datastructures_problem_store");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_datastructures_problem_query");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_datastructures_problem");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_datastructures_problem_link");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_datastructures_tactic");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_datastructures_proof");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_datastructures_strategy");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_datastructures_forward_propagate");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_datastructures_inference");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_czer");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_proof_spec");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_proof_spec_store");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker_answer");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker_restriction");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker_removal");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker_transformation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker_residual_transformation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker_rewrite");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker_split");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker_join_ordered");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker_join");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_worker_union");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_tactician_strategic_uninterestingness");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_lookahead_productivity");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_min_transformation_depth");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_tactician");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_tactician_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_strategic_heuristics");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_balanced_tactician_datastructures");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_balanced_tactician_strategic_uninterestingness");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_balanced_tactician_motivation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_balanced_tactician_execution");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_heuristic_balanced_tactician");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.balancing_tactician");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.removal_tactician_datastructures");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.removal_tactician_uninterestingness");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.removal_tactician_motivation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.removal_tactician_execution");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.removal_tactician");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.transformation_tactician_datastructures");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.transformation_tactician_uninterestingness");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.transformation_tactician_motivation");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.transformation_tactician_execution");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.transformation_tactician");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.new_root_tactician_datastructures");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.new_root_tactician_motivation");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.new_root_tactician_execution");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.new_root_tactician");
    SubLFiles.initialize("com.cyc.cycjava.cycl.neural_net");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_strategist");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_kernel");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_trivial");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_parameters");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_metrics");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_analysis");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_serialization");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.inference_unit_tests");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.removal_module_tests");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.transformation_module_tests");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.evaluatable_relation_tests");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.inference_testing_helpers");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.inference_testing");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.removal_module_cost_tests");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.kb_query");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.kbq_query_run");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.arete");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.janus");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.leviathan");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.deep_inference_generator");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.lilliput");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.lilliput_caches");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.ask_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.removal_module_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_lookup");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_minimization");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_evaluation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_symmetry");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_transitivity");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_reflexivity");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_reflexive_on");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_genlpreds_lookup");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_relation_all");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_relation_all_instance");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_relation_all_exists");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_relation_instance_exists");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_term_external_id_string");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_backchain_required");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_abduction");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.meta_removal_modules");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_non_wff");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_isa");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_genls");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_denotes");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_classification");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_subset_of");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_nearest_isa");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_disjointwith");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_termofunit");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_natfunction");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_formula_arg_n");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_equals");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_evaluate");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_different");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_genlmt");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_genlpreds");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_genlinverse");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_negationpreds");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_negationinverse");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_ist");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_consistent");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_admitted_formula");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_asserted_formula");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_asserted_arg1_binary_preds");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_function_corresponding_predicate");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_start_offset");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_true_sentence");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_formula_implies");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_asserted_more_specifically");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_isomorphic_sentences");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_conceptually_related");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_integer_between");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_indexical_referent");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_constant_name");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_assertion_mt");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_term_strings");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_perform_subl");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_term_chosen");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_tva_lookup");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_bookkeeping");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_rtv");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_member_of_list");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_assertion_arguments");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_deduction_supports");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_assertion_deductions");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_assertion_hl_asserted_argument_keyword");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_inference_reflection");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_known_antecedent_rule");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_distance_between");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_lat_long");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_country_of_city");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_kappa");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_interval_range");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_ke_useless_precision_value");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_kb_indexing");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_concatenate_strings");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_query_answers");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_set_of_list_with_same_member_in_pos");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_conjunctive_pruning");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_kb_sentence");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_source_sentence");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.transformation_modules");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.simplification_modules");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.rewrite_modules");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.forward");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.forward_modules");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.forward_propagate_assertions");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.abnormal");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.hl_prototypes");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.collection_intersection");
    SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.inference_abduction_utilities");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.abduction");
    SubLFiles.initialize("com.cyc.cycjava.cycl.fi");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_bookkeeping");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_kernel");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.harness.prove");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.inference_iterators");
    SubLFiles.initialize("com.cyc.cycjava.cycl.ke");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.api_remote_objects");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.batch_ke");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.inference_viewer");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.plot_generation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cardinality_estimates");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.relationship_generality_estimates");
    SubLFiles.initialize("com.cyc.cycjava.cycl.evaluation_defns");
    SubLFiles.initialize("com.cyc.cycjava.cycl.collection_defns");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.ke_utilities");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.ke_text");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.kb_ontology_utilities");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.ontology_layers");
    SubLFiles.initialize("com.cyc.cycjava.cycl.system_benchmarks");
 //   SubLFiles.initialize("com.cyc.cycjava.cycl.object_similarity");
 //   SubLFiles.initialize("com.cyc.cycjava.cycl.partitions");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.convert_partitions");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.core");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.kbs_utilities");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.kbs_identification");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.kbs_add_redundant");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.kbs_partition");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.kbs_cleanup");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.kbs_compare");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.kb_cleanup");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.genls_hierarchy_problems");
    SubLFiles.initialize("com.cyc.cycjava.cycl.encapsulation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.transcript_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.transcript_server");
    SubLFiles.initialize("com.cyc.cycjava.cycl.operation_communication");
    SubLFiles.initialize("com.cyc.cycjava.cycl.operation_queues");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.remote_operation_filters");
    SubLFiles.initialize("com.cyc.cycjava.cycl.user_actions");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.formula_template_vars");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.xml_vars");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.xml_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.agenda");
    SubLFiles.initialize("com.cyc.cycjava.cycl.subl_identifier");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.query_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_compare");
    SubLFiles.initialize("com.cyc.cycjava.cycl.kb_paths");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.ke_coherence");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.ke_tools");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.kb_filtering");
    SubLFiles.initialize("com.cyc.cycjava.cycl.xml_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.misc_kb_utilities");
    SubLFiles.initialize("com.cyc.cycjava.cycl.scientific_numbers");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.scientific_number_utilities");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.extended_numbers");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.arithmetic");
    SubLFiles.initialize("com.cyc.cycjava.cycl.hl_storage_module_declarations");
    SubLFiles.initialize("com.cyc.cycjava.cycl.bookkeeping_store");
    SubLFiles.initialize("com.cyc.cycjava.cycl.dumper");
    SubLFiles.initialize("com.cyc.cycjava.cycl.builder_utilities");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.gt_modules");
    SubLFiles.initialize("com.cyc.cycjava.cycl.task_processor");
    SubLFiles.initialize("com.cyc.cycjava.cycl.java_api_kernel");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.connection_guarding");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.open_cyc_simple_inference_api");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.term_classification_tree");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.ctest_macros");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.ctest_utils");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.kb_content_test.kct_variables");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.kb_content_test.kct_utils");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.kb_content_test.kct_cyc_testing");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.cyc_testing.kb_content_test.kct_thinking");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cycl_query_specification");
    SubLFiles.initialize("com.cyc.cycjava.cycl.new_cycl_query_specification");
    SubLFiles.initialize("com.cyc.cycjava.cycl.formula_templates");
    SubLFiles.initialize("com.cyc.cycjava.cycl.graphic_library_format");
    SubLFiles.initialize("com.cyc.cycjava.cycl.value_tables");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.script_instance_editor_api");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.similarity");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.constrained_term_finder");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.constraint_filters");
    SubLFiles.initialize("com.cyc.cycjava.cycl.test_query_suite");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.nl_api_datastructures");
    SubLFiles.initialize("com.cyc.cycjava.cycl.morphology");
    SubLFiles.initialize("com.cyc.cycjava.cycl.file_backed_cache_setup");
    SubLFiles.initialize("com.cyc.cycjava.cycl.standard_tokenization");
    SubLFiles.initialize("com.cyc.cycjava.cycl.interval_span");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_relevant_similar_queries");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.inference.modules.removal.removal_modules_semantically_related");
    SubLFiles.initialize("com.cyc.cycjava.cycl.folification");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.thcl");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.cycml");
    SubLFiles.initialize("com.cyc.cycjava.cycl.cycml_generator");
    SubLFiles.initialize("com.cyc.cycjava.cycl.concept_filter");
    SubLFiles.initialize("com.cyc.cycjava.cycl.lucene_session");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.quirk.quirk_trampolines");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.nlp_tests");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.properties");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.webcache");
    SubLFiles.initialize("com.cyc.cycjava.cycl.xref_database");
    SubLFiles.initialize("com.cyc.cycjava.cycl.secure_translation");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.form_translation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.file_translation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.system_translation");
  //  SubLFiles.initialize("com.cyc.cycjava.cycl.common_optimization");
    SubLFiles.initialize("com.cyc.cycjava.cycl.c_name_translation");
    SubLFiles.initialize("com.cyc.cycjava.cycl.c_backend");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.optimized_funcall_declarations");
    SubLFiles.initialize("com.cyc.cycjava.cycl.java_name_translation");
    //SubLFiles.initialize("com.cyc.cycjava.cycl.java_backend");
   // SubLFiles.initialize("com.cyc.cycjava.cycl.translator_utilities");
    SubLFiles.initialize("eu.larkc.core.orchestrator.LarkcInit");
    SubLFiles.initialize("eu.larkc.core.orchestrator.servers.LarKCHttpServer");
  }  
}