<wsdl:description>
	<!-- COMMON TO ALL SELECTERS -->
	<wsdl:interface name="infosetTransformer"
		sawsdl:modelReference="http://larkc.eu/plugin#InformationSetTransformer">
	</wsdl:interface>
	
	<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />

	<!-- SPECIFIC TO THIS IDENTIFIER -->
    <wsdl:service name="urn:eu.larkc.plugin.transform.passitontransformer.PassItOnTransformer" interface="infosetTransformer"
  	sawsdl:modelReference="eu/larkc/plugin/transform/passitontransformer/PassItOnTransformer.rdf#PassItOnTransformer" >
	    <wsdl:endpoint location="java:eu.larkc.plugin.transform.passitontransformer.PassItOnTransformer" />
    </wsdl:service>

</wsdl:description>