-- Drop all tables

DROP TABLE TEMPLATE_SUPPORT;
DROP TABLE TEMPLATE_VARIABLE_INTERPRETATION;
DROP TABLE TEMPLATE;
DROP TABLE TEMPLATE_PATTERN;
DROP TABLE INFERENCE_MODE;
DROP TABLE DOC_REF;
DROP TABLE DOC;
DROP TABLE INTERPRETATION_ISAS;
DROP TABLE INTERPRETATION_GENLS;
DROP TABLE CYCL;

-- Create tables

CREATE TABLE CYCL (
  ID int PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CYCL_EID varchar(8192),
  CYCL varchar(8192)
);

CREATE TABLE INFERENCE_MODE (
  ID int PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  MODE varchar(64) NOT NULL UNIQUE
);

CREATE TABLE DOC (
  ID int PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  URI varchar(4096) NOT NULL UNIQUE,
  DATE_PROCESSED timestamp NOT NULL
);

CREATE TABLE DOC_REF (
  ID int PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  DOC_ID int NOT NULL,
  CHAR_INDEX int,
  CHAR_LEN int,
  TOKEN_INDEX int,
  TOKEN_LENGTH int,
  STRING varchar(4096),
  CONSTRAINT DR_DOC_ID_FK FOREIGN KEY (DOC_ID) REFERENCES DOC (ID)
);

CREATE TABLE TEMPLATE_PATTERN (
  ID int PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ARG0 varchar(256),
  ARG1 varchar(256),
  ARG2 varchar(256),
  ARG3 varchar(256),
  ARG4 varchar(256),
  ARG5 varchar(256),
  ARG6 varchar(256),
  ARG7 varchar(256),
  ARG8 varchar(256),
  ARG9 varchar(256)
);

CREATE TABLE TEMPLATE (
  ID int PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TEMPLATE_PATTERN_ID int NOT NULL UNIQUE,
  MT_CYCL_ID int,
  INFERENCE_MODE_ID int,
  CYCL_PATTERN varchar(8192),
  CONSTRAINT T_TEMPLATE_PATTERN_ID_FK FOREIGN KEY (TEMPLATE_PATTERN_ID) REFERENCES TEMPLATE_PATTERN (ID),
  CONSTRAINT T_MT_CYCL_ID_FK FOREIGN KEY (MT_CYCL_ID) REFERENCES CYCL (ID),
  CONSTRAINT T_INFERENCE_MODE_ID_FK FOREIGN KEY (INFERENCE_MODE_ID) REFERENCES INFERENCE_MODE (ID)
);

CREATE TABLE TEMPLATE_SUPPORT (
  ID int PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  DOC_REF_ID int NOT NULL,
  TEMPLATE_ID int NOT NULL,
  CONSTRAINT TS_DOC_REF_ID_FK FOREIGN KEY (DOC_REF_ID) REFERENCES DOC_REF (ID),
  CONSTRAINT TS_TEMPLATE_ID_FK FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATE (ID)
);

CREATE TABLE TEMPLATE_VARIABLE_INTERPRETATION (
  TEMPLATE_ID int NOT NULL,
  ARG_INDEX int NOT NULL,
  CYCL_ID int NOT NULL,
  PRIMARY KEY (TEMPLATE_ID, ARG_INDEX, CYCL_ID),
  CONSTRAINT TVI_TEMPLATE_ID_FK FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATE (ID),
  CONSTRAINT TVI_CYCL_ID_FK FOREIGN KEY (CYCL_ID) REFERENCES CYCL (ID)
);

CREATE TABLE INTERPRETATION_ISAS (
  CYCL_ID int NOT NULL,
  ISA_CYCL_ID integer NOT NULL,
  MT_CYCL_ID integer NOT NULL,
  PRIMARY KEY (CYCL_ID, ISA_CYCL_ID, MT_CYCL_ID),
  CONSTRAINT II_CYCL_ID_FK FOREIGN KEY (CYCL_ID) REFERENCES CYCL (ID),
  CONSTRAINT II_ISA_CYCL_ID_FK FOREIGN KEY (ISA_CYCL_ID) REFERENCES CYCL (ID),
  CONSTRAINT II_MT_CYCL_ID_FK FOREIGN KEY (MT_CYCL_ID) REFERENCES CYCL (ID)
);

CREATE TABLE INTERPRETATION_GENLS (
  CYCL_ID int NOT NULL,
  GENL_CYCL_ID integer NOT NULL,
  MT_CYCL_ID integer NOT NULL,
  PRIMARY KEY (CYCL_ID, GENL_CYCL_ID, MT_CYCL_ID),
  CONSTRAINT IG_CYCL_ID_FK FOREIGN KEY (CYCL_ID) REFERENCES CYCL (ID),
  CONSTRAINT IG_GENL_CYCL_ID_FK FOREIGN KEY (GENL_CYCL_ID) REFERENCES CYCL (ID),
  CONSTRAINT IG_MT_CYCL_ID_FK FOREIGN KEY (MT_CYCL_ID) REFERENCES CYCL (ID)
);

-- Create default data

INSERT INTO INFERENCE_MODE ( MODE ) VALUES
  (':CUSTOM'),
  (':EXTENDED'),
  (':MAXIMAL'),
  (':MINIMAL'),
  (':SHALLOW'),
  (':MR_SKSI_QUERY_PARAMS_3');

-- Create indices

CREATE INDEX DOC_REF_DOC_ID_INDEX ON DOC_REF (DOC_ID);
CREATE INDEX DOC_REF_STRING_INDEX ON DOC_REF (STRING);

CREATE INDEX TEMPLATE_VARIABLE_INTERPRETATION_TEMPLATE_ID_INDEX ON TEMPLATE_VARIABLE_INTERPRETATION (TEMPLATE_ID);
CREATE INDEX TEMPLATE_VARIABLE_INTERPRETATION_ARG_INDEX_INDEX ON TEMPLATE_VARIABLE_INTERPRETATION (ARG_INDEX);
CREATE INDEX TEMPLATE_VARIABLE_INTERPRETATION_CYCL_ID_INDEX ON TEMPLATE_VARIABLE_INTERPRETATION (CYCL_ID);
CREATE INDEX TEMPLATE_VARIABLE_INTERPRETATION_TEMPLATE_ID_ARG_INDEX_INDEX ON TEMPLATE_VARIABLE_INTERPRETATION (TEMPLATE_ID, ARG_INDEX);
CREATE INDEX TEMPLATE_VARIABLE_INTERPRETATION_CYCL_ID_ARG_INDEX_INDEX ON TEMPLATE_VARIABLE_INTERPRETATION (CYCL_ID, ARG_INDEX);

CREATE INDEX INTERPRETATION_ISA_CYCL_ID_INDEX ON INTERPRETATION_ISAS (CYCL_ID);
CREATE INDEX INTERPRETATION_ISA_MT_CYCL_ID_INDEX ON INTERPRETATION_ISAS (MT_CYCL_ID);
CREATE INDEX INTERPRETATION_ISA_CYCL_MT_INDEX ON INTERPRETATION_ISAS (CYCL_ID, MT_CYCL_ID);
CREATE INDEX INTERPRETATION_ISA_CYCL_ID_INDEX ON INTERPRETATION_ISAS (ISA_CYCL_ID);

CREATE INDEX INTERPRETATION_GENL_CYCL_ID_INDEX ON INTERPRETATION_GENLS (CYCL_ID);
CREATE INDEX INTERPRETATION_GENL_MT_CYCL_ID_INDEX ON INTERPRETATION_GENLS (MT_CYCL_ID);
CREATE INDEX INTERPRETATION_GENL_CYL_MT_INDEX ON INTERPRETATION_GENLS (CYCL_ID, MT_CYCL_ID);
CREATE INDEX INTERPRETATION_GENL_CYCL_ID_INDEX ON INTERPRETATION_GENLS (GENL_CYCL_ID);

CREATE INDEX CYCL_EID_INDEX ON CYCL (CYCL_EID);
CREATE INDEX CYCL_EID_INDEX ON CYCL (CYCL_EID);

CREATE INDEX CYCL_EID_INDEX ON CYCL (CYCL_EID);
CREATE INDEX CYCL_INDEX ON CYCL (CYCL);

CREATE INDEX DOC_URI_INDEX ON DOC (URI);
CREATE INDEX DOC_DATE_INDEX ON DOC (DATE_PROCESSED);

CREATE INDEX TEMPLATE_ARG0_INDEX ON TEMPLATE_PATTERN (ARG0);
CREATE INDEX TEMPLATE_ARG1_INDEX ON TEMPLATE_PATTERN (ARG1);
CREATE INDEX TEMPLATE_ARG2_INDEX ON TEMPLATE_PATTERN (ARG2);
CREATE INDEX TEMPLATE_ARG3_INDEX ON TEMPLATE_PATTERN (ARG3);
CREATE INDEX TEMPLATE_ARG4_INDEX ON TEMPLATE_PATTERN (ARG4);
CREATE INDEX TEMPLATE_ARG5_INDEX ON TEMPLATE_PATTERN (ARG5);
CREATE INDEX TEMPLATE_ARG6_INDEX ON TEMPLATE_PATTERN (ARG6);
CREATE INDEX TEMPLATE_ARG7_INDEX ON TEMPLATE_PATTERN (ARG7);
CREATE INDEX TEMPLATE_ARG8_INDEX ON TEMPLATE_PATTERN (ARG8);
CREATE INDEX TEMPLATE_ARG9_INDEX ON TEMPLATE_PATTERN (ARG9);

CREATE INDEX TEMPLATE_ARGS_0_TO_1_INDEX ON TEMPLATE_PATTERN (ARG0, ARG1);
CREATE INDEX TEMPLATE_ARGS_0_TO_2_INDEX ON TEMPLATE_PATTERN (ARG0, ARG1, ARG2);
CREATE INDEX TEMPLATE_ARGS_0_TO_3_INDEX ON TEMPLATE_PATTERN (ARG0, ARG1, ARG2, ARG3);
CREATE INDEX TEMPLATE_ARGS_0_TO_4_INDEX ON TEMPLATE_PATTERN (ARG0, ARG1, ARG2, ARG3, ARG4);
CREATE INDEX TEMPLATE_ARGS_0_TO_5_INDEX ON TEMPLATE_PATTERN (ARG0, ARG1, ARG2, ARG3, ARG4, ARG5);
CREATE INDEX TEMPLATE_ARGS_0_TO_6_INDEX ON TEMPLATE_PATTERN (ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6);
CREATE INDEX TEMPLATE_ARGS_0_TO_7_INDEX ON TEMPLATE_PATTERN (ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7);
CREATE INDEX TEMPLATE_ARGS_0_TO_8_INDEX ON TEMPLATE_PATTERN (ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8);
CREATE INDEX TEMPLATE_ARGS_0_TO_9_INDEX ON TEMPLATE_PATTERN (ARG0, ARG1, ARG2, ARG3, ARG4, ARG5, ARG6, ARG7, ARG8, ARG9);

CREATE INDEX TEMPLATE_MT_CYCL_ID_INDEX ON TEMPLATE (MT_CYCL_ID);
CREATE INDEX TEMPLATE_INFERENCE_MODE_ID_INDEX ON TEMPLATE (INFERENCE_MODE_ID);
CREATE INDEX TEMPLATE_CYCL_PATTERN_INDEX ON TEMPLATE (CYCL_PATTERN);
CREATE INDEX TEMPLATE_TEMPLATE_PATTERN_ID_INDEX ON TEMPLATE (TEMPLATE_PATTERN_ID);
