<wsdl:description>
	<!-- COMMON TO ALL SELECTERS -->
	<wsdl:interface name="selecter"
		sawsdl:modelReference="http://larkc.eu/plugin#Selecter">
	</wsdl:interface>
	
	<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />

	<!-- SPECIFIC TO THIS IDENTIFIER -->
    <wsdl:service name="urn:PIONSelecter" interface="selecter"
  	sawsdl:modelReference="eu/larkc/plugin/select/simple/GrowingDataSetSelecter.rdf#PIONSelecter" >
	    <wsdl:endpoint location="java:eu.larkc.plugin.select.PIONSelecter" />
    </wsdl:service>

</wsdl:description>