<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ServiceGroup" targetNamespace="http://docs.oasis-open.org/wsrf/sgw-2/bindings" xmlns:porttype="http://docs.oasis-open.org/wsrf/sgw-2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://docs.oasis-open.org/wsrf/sgw-2" location="sgw-2.wsdl"/>
  <wsdl:binding name="ServiceGroupSOAPBinding" type="porttype:ServiceGroup">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetResourceProperty">
      <soap:operation soapAction="http://docs.oasis-open.org/wsrf/sgw-2/ServiceGroup/GetResourcePropertyRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvalidResourcePropertyQNameFault">
        <soap:fault name="InvalidResourcePropertyQNameFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnavailableFault">
        <soap:fault name="ResourceUnavailableFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ServiceGroupRegistrationSOAPBinding" type="porttype:ServiceGroupRegistration">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetResourceProperty">
      <soap:operation soapAction="http://docs.oasis-open.org/wsrf/sgw-2/ServiceGroupRegistration/GetResourcePropertyRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvalidResourcePropertyQNameFault">
        <soap:fault name="InvalidResourcePropertyQNameFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnavailableFault">
        <soap:fault name="ResourceUnavailableFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="Add">
      <soap:operation soapAction="http://docs.oasis-open.org/wsrf/sgw-2/ServiceGroupRegistration/AddRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ContentCreationFailedFault">
        <soap:fault name="ContentCreationFailedFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnsupportedMemberInterfaceFault">
        <soap:fault name="UnsupportedMemberInterfaceFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="AddRefusedFault">
        <soap:fault name="AddRefusedFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnavailableFault">
        <soap:fault name="ResourceUnavailableFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ServiceGroupEntrySOAPBinding" type="porttype:ServiceGroupEntry">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetResourceProperty">
      <soap:operation soapAction="http://docs.oasis-open.org/wsrf/sgw-2/ServiceGroupEntry/GetResourcePropertyRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvalidResourcePropertyQNameFault">
        <soap:fault name="InvalidResourcePropertyQNameFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnavailableFault">
        <soap:fault name="ResourceUnavailableFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
