<wsdl:description>
<wsdl:interface name="Identifier"
	sawsdl:modelReference="http://larkc.eu/plugin#Identifier">
</wsdl:interface>
<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />
<!-- SPECIFIC TO THIS PLUGIN_TYPE -->
<wsdl:service name="urn:GoogleCalendarIdentifier" interface="Identifier"
sawsdl:modelReference="http://larkc.eu/plugin#GoogleCalendarIdentifier" >
    <wsdl:endpoint location="java:eu.larkc.plugin.identify.GoogleCalendarIdentifier" />
</wsdl:service>
</wsdl:description>
