#!/bin/sh

# abcl.in

# Copyright (C) 2004 Peter Graves
# Copyright (C) 2009 Erik Huelsmann

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

exec /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java \
   -server -cp  /mnt/gggg/PrologMUD/pack/larkc_cl/jrtl-clabcl/dist/abcl.jar:/mnt/gggg/PrologMUD/pack/larkc_cl/jrtl-cl/target/classes:"$CLASSPATH" \
   -d64 -Xms5000m -Xmx8000m -XX:ReservedCodeCacheSize=96m  -XX:+DoEscapeAnalysis -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC \
   -agentlib:jdwp=transport=dt_socket,server=y,address=3619,suspend=n \
  org.armedbear.lisp.Main \
  "$@"

