<wsdl:description>
	<!-- COMMON TO ALL SELECTERS -->
	<wsdl:interface name="selecter"
		sawsdl:modelReference="http://larkc.eu/plugin#Selecter">
	</wsdl:interface>
	
	<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />

	<!-- SPECIFIC TO THIS IDENTIFIER -->
    <wsdl:service name="urn:eu.larkc.plugin.select.RandomIndexingSelecter" interface="selecter"
  	sawsdl:modelReference="http://larkc.eu/plugin#RandomIndexingSelecter" >
	    <wsdl:endpoint location="java:eu.larkc.plugin.select.RandomIndexingSelecter" />
    </wsdl:service>

</wsdl:description>