<wsdl:description>
	<!-- COMMON TO ALL DECIDERS -->
	<wsdl:interface name="decider"
		sawsdl:modelReference="http://larkc.eu/plugin#Decider">
	</wsdl:interface>
	
	<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />

	<!-- SPECIFIC TO THIS DECIDER -->
    <wsdl:service name="urn:PIONDecider" interface="decider"
  	sawsdl:modelReference="http://larkc.eu/plugin#PIONDecider" >
	    <wsdl:endpoint location="java:eu.larkc.plugin.decider.PIONDecider" />
    </wsdl:service>

</wsdl:description>