/* $Id: InferenceWorkerListener.java 150734 2014-04-24 22:32:49Z nwinant $
 */

package com.cyc.base.inference;

import java.util.EventListener; 
import java.util.List;

/** *  <P> This interface is one that must be implemented by anyone
 * wishing to listen in on events generated by a InferenceWorker.
 *
 * @see InferenceWorker
 * @author tbrussea, zelal
 * @version $Id: InferenceWorkerListener.java 150734 2014-04-24 22:32:49Z nwinant $
 */
public interface InferenceWorkerListener extends EventListener {
  
  public void notifyInferenceCreated(InferenceWorker inferenceWorker);
  
  public void notifyInferenceStatusChanged(InferenceStatus oldStatus, InferenceStatus newStatus, 
    InferenceSuspendReason suspendReason, InferenceWorker inferenceWorker);
  
  public void notifyInferenceAnswersAvailable(InferenceWorker inferenceWorker, List newAnswers);

  public void notifyInferenceTerminated(InferenceWorker inferenceWorker, Exception e);

}
