<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="WS-BaseNotification" targetNamespace="http://docs.oasis-open.org/wsn/bw-2/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://docs.oasis-open.org/wsn/bw-2/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://docs.oasis-open.org/wsn/bw-2/bindings" location="WS-BaseN_bindings.wsdl"/>
  <wsdl:service name="WS-BaseNotificationService">
    <wsdl:port name="NotificationProducerPort" binding="binding:NotificationProducerSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="PausableSubscriptionManagerPort" binding="binding:PausableSubscriptionManagerSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="PullPointPort" binding="binding:PullPointSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="SubscriptionManagerPort" binding="binding:SubscriptionManagerSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="NotificationConsumerPort" binding="binding:NotificationConsumerSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="CreatePullPointPort" binding="binding:CreatePullPointSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
