<wsdl:description>
	<!-- COMMON TO ALL SELECTERS -->
	<wsdl:interface name="identifier"
		sawsdl:modelReference="http://larkc.eu/plugin#Identifier">
	</wsdl:interface>
	
	<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />

	<!-- SPECIFIC TO THIS IDENTIFIER -->
    <wsdl:service name="urn:template_identifier" interface="identifier"
  	sawsdl:modelReference="http://larkc.eu/plugin#template_identifier" >
	    <wsdl:endpoint location="java:eu.larkc.plugin.identify.template_identifier" />
    </wsdl:service>

</wsdl:description>