<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TestAuthz" targetNamespace="http://www.globus.org/gram/authz/test" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.globus.org/gram/authz/test" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://www.globus.org/gram/authz/test" xmlns:tns="http://www.globus.org/gram/authz/test" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

        <xsd:element name="test">
            <xsd:complexType/>
        </xsd:element>

        <xsd:element name="testOutput">
            <xsd:complexType/>
        </xsd:element>
        </xsd:schema>
  </types>
  <message name="TestRequest">
    <part name="request" element="tns:test"/>
  </message>
  <message name="TestResponse">
    <part name="response" element="tns:testOutput"/>
  </message>
  <portType name="TestAuthzPortType">
    <operation name="test">
      <input message="tns:TestRequest"/>
      <output message="tns:TestResponse"/>
    </operation>
  </portType>
</definitions>
