<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TestAuthz" targetNamespace="http://www.globus.org/gram/authz/test/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:porttype="http://www.globus.org/gram/authz/test" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://www.globus.org/gram/authz/test" location="authz_test_flattened.wsdl"/>
  <wsdl:binding name="TestAuthzPortTypeSOAPBinding" type="porttype:TestAuthzPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="test">
      <soap:operation soapAction="http://www.globus.org/gram/authz/test/TestAuthzPortType/testRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
