<wsdl:description>
	<!-- COMMON TO ALL SELECTERS -->
	<wsdl:interface name="reasoner"
		sawsdl:modelReference="http://larkc.eu/plugin#Reasoner">
	</wsdl:interface>
	
	<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />

	<!-- SPECIFIC TO THIS IDENTIFIER -->
    <wsdl:service name="urn:SparqlQueryEvaluationReasoner" interface="reasoner"
  	sawsdl:modelReference="http://larkc.eu/plugin#SparqlQueryEvaluationReasoner" >
	    <wsdl:endpoint location="java:eu.larkc.plugin.reason.simple.SparqlQueryEvaluationReasoner" />
    </wsdl:service>
</wsdl:description>