<wsdl:description>
	<!-- COMMON TO ALL SELECTERS -->
	<wsdl:interface name="selecter"
		sawsdl:modelReference="http://larkc.eu/plugin#Reasoner">
	</wsdl:interface>
	
	<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />

	<!-- SPECIFIC TO THIS IDENTIFIER -->
    <wsdl:service name="urn:eu.larkc.plugin.reason.irisrulereasoner.IrisRuleBasedReasoner" interface="reasoner"
  	sawsdl:modelReference="eu/larkc/plugin/reason/irisrulereasoner/IrisRuleBasedReasoner.rdf#IrisRuleBasedReasoner" >
	    <wsdl:endpoint location="java:eu.larkc.plugin.reason.irisrulereasoner.IrisRuleBasedReasoner" />
    </wsdl:service>

</wsdl:description>