/* Generated By:JavaCC: Do not edit this line. SubLParserTokenManager.java */
package com.cyc.tool.subl.parser;

public class SubLParserTokenManager implements SubLParserConstants {
	static long[] jjbitVec0 = { 0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL };

	static int[] jjnextStates = { 12, 13, 15, 31, 36, 37, 161, 7, 8, 10, 20, 21, 23, 26, 1, 27, 28, 20, 26, 1, 27, 20,
			21, 23, 38, 41, 43, 47, 49, 50, 51, 63, 77, 90, 93, 104, 113, 124, 125, 134, 137, 38, 41, 43, 47, 49, 50,
			51, 63, 77, 90, 93, 104, 113, 124, 125, 134, 137, 148, 162, 163, 164, 162, 163, 164, 169, 38, 41, 43, 47,
			49, 50, 51, 63, 77, 90, 93, 104, 113, 124, 125, 137, 148, 153, 4, 5, 24, 25, 41, 43, 47, 49, 50, 51, 63, 77,
			90, 93, 104, 113, 124, 125, 134, 137, 54, 55, 60, 52, 62, 65, 67, 68, 69, 71, 72, 75, 76, 78, 79, 81, 82,
			83, 87, 89, 91, 92, 95, 96, 103, 48, 129, 48, 133, 138, 140, 142, 144, 146, 147, 160, 154, 135, 136, };

	public static String[] jjstrLiteralImages = { "", "\50", "\51", "\72", "\174", "\43\50", "\43\47", "\47", "\140",
			"\54\100", "\54", "\56", "\42", "\43\72", "\43\56", "\43\53", "\43\55", null, null, null, null, null, null,
			null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
			null, null, null, null, null, null, };

	public static String[] lexStateNames = { "DEFAULT", "IN_SINGLE_LINE_COMMENT", "IN_MULTI_LINE_COMMENT", };

	public static int[] jjnewLexState = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
			-1, 1, 2, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
			-1, };

	static long[] jjtoToken = { 0x4c066e01ffffL, };

	static long[] jjtoSkip = { 0xc00000L, };

	static long[] jjtoSpecial = { 0xc00000L, };

	static long[] jjtoMore = { 0x1300000L, };

	private ASCII_CharStream input_stream;

	private int[] jjrounds = new int[177];

	private int[] jjstateSet = new int[354];

	StringBuilder image;

	int jjimageLen;

	int lengthOfMatch;

	protected char curChar;

	int curLexState = 0;

	int defaultLexState = 0;
	int jjnewStateCnt;
	int jjround;
	int jjmatchedPos;
	int jjmatchedKind;

	public SubLParserTokenManager(ASCII_CharStream stream) {
		if (ASCII_CharStream.staticFlag)
			throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
		this.input_stream = stream;
	}

	public SubLParserTokenManager(ASCII_CharStream stream, int lexState) {
		this(stream);
		this.SwitchTo(lexState);
	}

	public Token getNextToken() {
		int kind;
		Token specialToken = null;
		Token matchedToken;
		int curPos = 0;

		EOFLoop: for (;;) {
			try {
				this.curChar = this.input_stream.BeginToken();
			} catch (java.io.IOException e) {
				this.jjmatchedKind = 0;
				matchedToken = this.jjFillToken();
				matchedToken.specialToken = specialToken;
				return matchedToken;
			}
			this.image = null;
			this.jjimageLen = 0;

			for (;;) {
				switch (this.curLexState) {
				case 0:
					this.jjmatchedKind = 0x7fffffff;
					this.jjmatchedPos = 0;
					curPos = this.jjMoveStringLiteralDfa0_0();
					break;
				case 1:
					this.jjmatchedKind = 0x7fffffff;
					this.jjmatchedPos = 0;
					curPos = this.jjMoveStringLiteralDfa0_1();
					if (this.jjmatchedPos == 0 && this.jjmatchedKind > 24)
						this.jjmatchedKind = 24;
					break;
				case 2:
					this.jjmatchedKind = 0x7fffffff;
					this.jjmatchedPos = 0;
					curPos = this.jjMoveStringLiteralDfa0_2();
					if (this.jjmatchedPos == 0 && this.jjmatchedKind > 24)
						this.jjmatchedKind = 24;
					break;
				}
				if (this.jjmatchedKind != 0x7fffffff) {
					if (this.jjmatchedPos + 1 < curPos)
						this.input_stream.backup(curPos - this.jjmatchedPos - 1);
					if ((SubLParserTokenManager.jjtoToken[this.jjmatchedKind >> 6]
							& 1L << (this.jjmatchedKind & 077)) != 0L) {
						matchedToken = this.jjFillToken();
						matchedToken.specialToken = specialToken;
						if (SubLParserTokenManager.jjnewLexState[this.jjmatchedKind] != -1)
							this.curLexState = SubLParserTokenManager.jjnewLexState[this.jjmatchedKind];
						return matchedToken;
					} else if ((SubLParserTokenManager.jjtoSkip[this.jjmatchedKind >> 6]
							& 1L << (this.jjmatchedKind & 077)) != 0L) {
						if ((SubLParserTokenManager.jjtoSpecial[this.jjmatchedKind >> 6]
								& 1L << (this.jjmatchedKind & 077)) != 0L) {
							matchedToken = this.jjFillToken();
							if (specialToken == null)
								specialToken = matchedToken;
							else {
								matchedToken.specialToken = specialToken;
								specialToken = specialToken.next = matchedToken;
							}
							this.SkipLexicalActions(matchedToken);
						} else
							this.SkipLexicalActions(null);
						if (SubLParserTokenManager.jjnewLexState[this.jjmatchedKind] != -1)
							this.curLexState = SubLParserTokenManager.jjnewLexState[this.jjmatchedKind];
						continue EOFLoop;
					}
					this.jjimageLen += this.jjmatchedPos + 1;
					if (SubLParserTokenManager.jjnewLexState[this.jjmatchedKind] != -1)
						this.curLexState = SubLParserTokenManager.jjnewLexState[this.jjmatchedKind];
					curPos = 0;
					this.jjmatchedKind = 0x7fffffff;
					try {
						this.curChar = this.input_stream.readChar();
						continue;
					} catch (java.io.IOException e1) {
					}
				}
				int error_line = this.input_stream.getEndLine();
				int error_column = this.input_stream.getEndColumn();
				String error_after = null;
				boolean EOFSeen = false;
				try {
					this.input_stream.readChar();
					this.input_stream.backup(1);
				} catch (java.io.IOException e1) {
					EOFSeen = true;
					error_after = curPos <= 1 ? "" : this.input_stream.GetImage();
					if (this.curChar == '\n' || this.curChar == '\r') {
						error_line++;
						error_column = 0;
					} else
						error_column++;
				}
				if (!EOFSeen) {
					this.input_stream.backup(1);
					error_after = curPos <= 1 ? "" : this.input_stream.GetImage();
				}
				throw new TokenMgrError(EOFSeen, this.curLexState, error_line, error_column, error_after, this.curChar,
						TokenMgrError.LEXICAL_ERROR);
			}
		}
	}

	private void jjAddStates(int start, int end) {
		do
			this.jjstateSet[this.jjnewStateCnt++] = SubLParserTokenManager.jjnextStates[start];
		while (start++ != end);
	}

	private void jjCheckNAdd(int state) {
		if (this.jjrounds[state] != this.jjround) {
			this.jjstateSet[this.jjnewStateCnt++] = state;
			this.jjrounds[state] = this.jjround;
		}
	}

	private void jjCheckNAddStates(int start) {
		this.jjCheckNAdd(SubLParserTokenManager.jjnextStates[start]);
		this.jjCheckNAdd(SubLParserTokenManager.jjnextStates[start + 1]);
	}

	private void jjCheckNAddStates(int start, int end) {
		do
			this.jjCheckNAdd(SubLParserTokenManager.jjnextStates[start]);
		while (start++ != end);
	}

	private void jjCheckNAddTwoStates(int state1, int state2) {
		this.jjCheckNAdd(state1);
		this.jjCheckNAdd(state2);
	}

	private Token jjFillToken() {
		Token t = Token.newToken(this.jjmatchedKind);
		t.kind = this.jjmatchedKind;
		String im = SubLParserTokenManager.jjstrLiteralImages[this.jjmatchedKind];
		t.image = im == null ? this.input_stream.GetImage() : im;
		t.beginLine = this.input_stream.getBeginLine();
		t.beginColumn = this.input_stream.getBeginColumn();
		t.endLine = this.input_stream.getEndLine();
		t.endColumn = this.input_stream.getEndColumn();
		return t;
	}

	private int jjMoveNfa_0(int startState, int curPos) {
		int[] nextStates;
		int startsAt = 0;
		this.jjnewStateCnt = 177;
		int i = 1;
		this.jjstateSet[0] = startState;
		int j, kind = 0x7fffffff;
		for (;;) {
			if (++this.jjround == 0x7fffffff)
				this.ReInitRounds();
			if (this.curChar < 64) {
				long l = 1L << this.curChar;
				MatchLoop: do
					switch (this.jjstateSet[--i]) {
					case 178:
					case 12:
					case 14:
						this.jjCheckNAddStates(0, 2);
						break;
					case 0:
						if ((0xf3ffec7200000000L & l) != 0L) {
							if (kind > 46)
								kind = 46;
							this.jjCheckNAddTwoStates(16, 18);
						} else if ((0x100003600L & l) != 0L) {
							if (kind > 25)
								kind = 25;
						} else if (this.curChar == 35)
							this.jjAddStates(3, 6);
						else if (this.curChar == 34)
							this.jjCheckNAddStates(7, 9);
						if ((0x3ff000000000000L & l) != 0L) {
							if (kind > 29)
								kind = 29;
							this.jjCheckNAddStates(10, 16);
						} else if ((0x280000000000L & l) != 0L)
							this.jjCheckNAddStates(17, 20);
						else if (this.curChar == 46)
							this.jjCheckNAdd(2);
						break;
					case 177:
						if ((0xfffffffbffffffffL & l) != 0L)
							this.jjCheckNAddStates(7, 9);
						else if (this.curChar == 34)
							if (kind > 42)
								kind = 42;
						break;
					case 31:
						if ((0x3ff000000000000L & l) != 0L)
							this.jjCheckNAddTwoStates(32, 33);
						break;
					case 179:
						if ((0xf3ffec7200000000L & l) != 0L) {
							if (kind > 46)
								kind = 46;
							this.jjCheckNAddTwoStates(16, 18);
						}
						if ((0x3ff000000000000L & l) != 0L) {
							if (kind > 27)
								kind = 27;
							this.jjCheckNAddTwoStates(2, 3);
						}
						break;
					case 1:
						if (this.curChar == 46)
							this.jjCheckNAdd(2);
						break;
					case 2:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 27)
							kind = 27;
						this.jjCheckNAddTwoStates(2, 3);
						break;
					case 4:
						if ((0x280000000000L & l) != 0L)
							this.jjCheckNAdd(5);
						break;
					case 5:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 27)
							kind = 27;
						this.jjCheckNAdd(5);
						break;
					case 6:
						if (this.curChar == 34)
							this.jjCheckNAddStates(7, 9);
						break;
					case 7:
						if ((0xfffffffbffffffffL & l) != 0L)
							this.jjCheckNAddStates(7, 9);
						break;
					case 9:
						this.jjCheckNAddStates(7, 9);
						break;
					case 10:
						if (this.curChar == 34 && kind > 42)
							kind = 42;
						break;
					case 17:
						if (kind > 46)
							kind = 46;
						this.jjCheckNAddTwoStates(16, 18);
						break;
					case 18:
						if ((0xf3ffec7200000000L & l) == 0L)
							break;
						if (kind > 46)
							kind = 46;
						this.jjCheckNAddTwoStates(16, 18);
						break;
					case 19:
						if ((0x280000000000L & l) != 0L)
							this.jjCheckNAddStates(17, 20);
						break;
					case 20:
						if ((0x3ff000000000000L & l) != 0L)
							this.jjCheckNAddStates(21, 23);
						break;
					case 21:
						if (this.curChar == 46)
							this.jjCheckNAddTwoStates(22, 23);
						break;
					case 22:
						if ((0x3ff000000000000L & l) != 0L)
							this.jjCheckNAddTwoStates(22, 23);
						break;
					case 24:
						if ((0x280000000000L & l) != 0L)
							this.jjCheckNAdd(25);
						break;
					case 25:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 26)
							kind = 26;
						this.jjCheckNAdd(25);
						break;
					case 26:
						if ((0x3ff000000000000L & l) != 0L)
							this.jjCheckNAddTwoStates(26, 1);
						break;
					case 27:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 29)
							kind = 29;
						this.jjCheckNAddTwoStates(27, 28);
						break;
					case 28:
						if (this.curChar == 46 && kind > 29)
							kind = 29;
						break;
					case 29:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 29)
							kind = 29;
						this.jjCheckNAddStates(10, 16);
						break;
					case 30:
						if (this.curChar == 35)
							this.jjAddStates(3, 6);
						break;
					case 32:
						if ((0x3ff000000000000L & l) != 0L)
							this.jjCheckNAdd(33);
						break;
					case 34:
						if ((0x280000000000L & l) != 0L)
							this.jjCheckNAdd(35);
						break;
					case 35:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 30)
							kind = 30;
						this.jjCheckNAdd(35);
						break;
					case 116:
						if (this.curChar == 45)
							this.jjstateSet[this.jjnewStateCnt++] = 115;
						break;
					case 139:
						if (this.curChar == 49 && kind > 33)
							kind = 33;
						break;
					case 141:
						if (this.curChar == 50 && kind > 33)
							kind = 33;
						break;
					case 143:
						if (this.curChar == 51 && kind > 33)
							kind = 33;
						break;
					case 145:
						if (this.curChar == 52 && kind > 33)
							kind = 33;
						break;
					case 149:
						if (this.curChar == 45)
							this.jjCheckNAddStates(24, 40);
						break;
					case 154:
						if (this.curChar == 45)
							this.jjCheckNAddStates(41, 58);
						break;
					case 163:
						if ((0xfffffffe00000000L & l) != 0L && kind > 34)
							kind = 34;
						break;
					case 165:
						if (this.curChar == 45)
							this.jjCheckNAddTwoStates(162, 163);
						break;
					case 170:
						if (this.curChar == 45)
							this.jjCheckNAddStates(59, 61);
						break;
					default:
						break;
					}
				while (i != startsAt);
			} else if (this.curChar < 128) {
				long l = 1L << (this.curChar & 077);
				MatchLoop: do
					switch (this.jjstateSet[--i]) {
					case 178:
						if ((0xefffffffefffffffL & l) != 0L)
							this.jjCheckNAddStates(0, 2);
						else if (this.curChar == 92)
							this.jjstateSet[this.jjnewStateCnt++] = 14;
						break;
					case 0:
						if ((0x6ffffffeefffffffL & l) != 0L) {
							if (kind > 46)
								kind = 46;
							this.jjCheckNAddTwoStates(16, 18);
						} else if (this.curChar == 92)
							this.jjstateSet[this.jjnewStateCnt++] = 17;
						else if (this.curChar == 124)
							this.jjCheckNAddTwoStates(12, 13);
						break;
					case 177:
						if ((0xffffffffefffffffL & l) != 0L)
							this.jjCheckNAddStates(7, 9);
						else if (this.curChar == 92)
							this.jjstateSet[this.jjnewStateCnt++] = 9;
						break;
					case 31:
						if ((0x100800401008004L & l) != 0L)
							this.jjCheckNAddTwoStates(34, 35);
						else if (this.curChar == 92)
							this.jjCheckNAddStates(62, 65);
						if (this.curChar == 92)
							this.jjCheckNAddStates(66, 83);
						break;
					case 179:
						if ((0x6ffffffeefffffffL & l) != 0L) {
							if (kind > 46)
								kind = 46;
							this.jjCheckNAddTwoStates(16, 18);
						} else if (this.curChar == 92)
							this.jjstateSet[this.jjnewStateCnt++] = 17;
						break;
					case 3:
						if ((0x8107000081070L & l) != 0L)
							this.jjAddStates(84, 85);
						break;
					case 7:
						if ((0xffffffffefffffffL & l) != 0L)
							this.jjCheckNAddStates(7, 9);
						break;
					case 8:
						if (this.curChar == 92)
							this.jjstateSet[this.jjnewStateCnt++] = 9;
						break;
					case 9:
						this.jjCheckNAddStates(7, 9);
						break;
					case 11:
						if (this.curChar == 124)
							this.jjCheckNAddTwoStates(12, 13);
						break;
					case 12:
						if ((0xefffffffefffffffL & l) != 0L)
							this.jjCheckNAddStates(0, 2);
						break;
					case 13:
						if (this.curChar == 92)
							this.jjstateSet[this.jjnewStateCnt++] = 14;
						break;
					case 14:
						this.jjCheckNAddStates(0, 2);
						break;
					case 15:
						if (this.curChar == 124 && kind > 43)
							kind = 43;
						break;
					case 16:
						if (this.curChar == 92)
							this.jjstateSet[this.jjnewStateCnt++] = 17;
						break;
					case 17:
						if (kind > 46)
							kind = 46;
						this.jjCheckNAddTwoStates(16, 18);
						break;
					case 18:
						if ((0x6ffffffeefffffffL & l) == 0L)
							break;
						if (kind > 46)
							kind = 46;
						this.jjCheckNAddTwoStates(16, 18);
						break;
					case 23:
						if ((0x8107000081070L & l) != 0L)
							this.jjAddStates(86, 87);
						break;
					case 33:
						if ((0x4000000040000L & l) != 0L)
							this.jjCheckNAddTwoStates(34, 35);
						break;
					case 35:
						if ((0x7fffffe07fffffeL & l) == 0L)
							break;
						if (kind > 30)
							kind = 30;
						this.jjCheckNAdd(35);
						break;
					case 36:
						if ((0x100800401008004L & l) != 0L)
							this.jjCheckNAddTwoStates(34, 35);
						break;
					case 37:
						if (this.curChar == 92)
							this.jjCheckNAddStates(66, 83);
						break;
					case 38:
						if (this.curChar == 92)
							this.jjCheckNAddStates(88, 103);
						break;
					case 39:
						if ((0x400000004L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 40:
					case 114:
						if ((0x200000002L & l) != 0L)
							this.jjCheckNAdd(39);
						break;
					case 41:
						if ((0x10000000100000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 40;
						break;
					case 42:
						if ((0x10000000100000L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 43:
						if ((0x10000000100L & l) != 0L)
							this.jjCheckNAdd(42);
						break;
					case 44:
						if ((0x2000000020L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 45:
						if ((0x8000000080L & l) != 0L)
							this.jjCheckNAdd(44);
						break;
					case 46:
						if ((0x200000002L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 45;
						break;
					case 47:
						if ((0x1000000010000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 46;
						break;
					case 48:
						if ((0x8000000080000L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 49:
						if ((0x8000000080L & l) != 0L)
							this.jjCheckNAdd(48);
						break;
					case 50:
						if ((0x20000000200000L & l) != 0L)
							this.jjCheckNAdd(48);
						break;
					case 51:
						if ((0x400000004000L & l) != 0L)
							this.jjCheckNAddStates(104, 108);
						break;
					case 52:
						if ((0x100000001000L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 53:
					case 94:
						if ((0x100000001000L & l) != 0L)
							this.jjCheckNAdd(52);
						break;
					case 54:
						if ((0x20000000200000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 53;
						break;
					case 55:
						if ((0x20000000200000L & l) != 0L)
							this.jjCheckNAdd(52);
						break;
					case 56:
						if ((0x400000004000L & l) != 0L)
							this.jjCheckNAdd(44);
						break;
					case 57:
						if ((0x20000000200L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 56;
						break;
					case 58:
						if ((0x100000001000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 57;
						break;
					case 59:
						if ((0x80000000800000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 58;
						break;
					case 60:
						if ((0x2000000020L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 59;
						break;
					case 61:
						if ((0x80000000800L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 62:
						if ((0x200000002L & l) != 0L)
							this.jjCheckNAdd(61);
						break;
					case 63:
						if ((0x8000000080000L & l) != 0L)
							this.jjAddStates(109, 116);
						break;
					case 64:
						if ((0x10000000100L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 65:
						if ((0x800000008000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 64;
						break;
					case 66:
						if ((0x100000001000000L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 67:
					case 78:
						if ((0x10000000100000L & l) != 0L)
							this.jjCheckNAdd(66);
						break;
					case 68:
						if ((0x800000008000L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 69:
						if ((0x20000000200L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 70:
						if ((0x400000004000L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 71:
						if ((0x200000002000000L & l) != 0L)
							this.jjCheckNAdd(70);
						break;
					case 72:
						if ((0x20000000200000L & l) != 0L)
							this.jjCheckNAdd(39);
						break;
					case 73:
					case 97:
						if ((0x800000008L & l) != 0L)
							this.jjCheckNAdd(44);
						break;
					case 74:
						if ((0x200000002L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 73;
						break;
					case 75:
						if ((0x1000000010000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 74;
						break;
					case 76:
						if ((0x1000000010000L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 77:
						if ((0x2000000020L & l) != 0L)
							this.jjAddStates(117, 123);
						break;
					case 79:
						if ((0x800000008000L & l) != 0L)
							this.jjCheckNAdd(42);
						break;
					case 80:
						if ((0x2000000020000L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 81:
						if ((0x400000004000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 80;
						break;
					case 82:
						if ((0x10000000100000L & l) != 0L)
							this.jjCheckNAdd(39);
						break;
					case 83:
						if ((0x200000002000L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 84:
						if ((0x1000000010000L & l) != 0L)
							this.jjCheckNAdd(44);
						break;
					case 85:
						if ((0x200000002L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 84;
						break;
					case 86:
						if ((0x800000008L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 85;
						break;
					case 87:
						if ((0x8000000080000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 86;
						break;
					case 88:
						if ((0x800000008L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 89:
						if ((0x8000000080000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 88;
						break;
					case 90:
						if ((0x200000002L & l) != 0L)
							this.jjAddStates(124, 125);
						break;
					case 91:
						if ((0x800000008L & l) != 0L)
							this.jjCheckNAdd(61);
						break;
					case 92:
						if ((0x100000001000L & l) != 0L)
							this.jjCheckNAdd(42);
						break;
					case 93:
						if ((0x400000004L & l) != 0L)
							this.jjCheckNAddStates(126, 129);
						break;
					case 95:
						if ((0x2000000020L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 94;
						break;
					case 96:
					case 147:
						if ((0x2000000020L & l) != 0L)
							this.jjCheckNAdd(52);
						break;
					case 98:
						if ((0x200000002L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 97;
						break;
					case 99:
						if ((0x1000000010000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 98;
						break;
					case 100:
						if ((0x8000000080000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 99;
						break;
					case 101:
						if ((0x80000000800L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 100;
						break;
					case 102:
						if ((0x800000008L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 101;
						break;
					case 103:
						if ((0x200000002L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 102;
						break;
					case 104:
						if ((0x100000001000L & l) != 0L)
							this.jjCheckNAddTwoStates(111, 112);
						break;
					case 105:
						if ((0x1000000010L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 106:
						if ((0x2000000020L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 105;
						break;
					case 107:
						if ((0x2000000020L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 106;
						break;
					case 108:
						if ((0x4000000040L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 107;
						break;
					case 109:
						if ((0x2000000020L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 108;
						break;
					case 110:
						if ((0x400000004000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 109;
						break;
					case 111:
						if ((0x20000000200L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 110;
						break;
					case 112:
						if ((0x4000000040L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 113:
						if ((0x40000000400000L & l) != 0L)
							this.jjCheckNAddTwoStates(123, 42);
						break;
					case 115:
						if ((0x10000000100000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 114;
						break;
					case 117:
						if ((0x100000001000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 116;
						break;
					case 118:
						if ((0x200000002L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 117;
						break;
					case 119:
						if ((0x800000008L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 118;
						break;
					case 120:
						if ((0x20000000200L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 119;
						break;
					case 121:
						if ((0x10000000100000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 120;
						break;
					case 122:
						if ((0x4000000040000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 121;
						break;
					case 123:
						if ((0x2000000020L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 122;
						break;
					case 124:
						if ((0x4000000040L & l) != 0L)
							this.jjCheckNAddTwoStates(112, 48);
						break;
					case 125:
						if ((0x4000000040000L & l) != 0L)
							this.jjCheckNAddStates(130, 132);
						break;
					case 126:
						if ((0x4000000040000L & l) != 0L)
							this.jjCheckNAdd(70);
						break;
					case 127:
						if ((0x20000000200000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 126;
						break;
					case 128:
						if ((0x10000000100000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 127;
						break;
					case 129:
						if ((0x2000000020L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 128;
						break;
					case 130:
						if ((0x20000000200000L & l) != 0L)
							this.jjCheckNAdd(42);
						break;
					case 131:
						if ((0x800000008000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 130;
						break;
					case 132:
						if ((0x400000004L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 131;
						break;
					case 133:
						if ((0x20000000200000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 132;
						break;
					case 134:
						if ((0x800000008L & l) != 0L)
							this.jjCheckNAddTwoStates(135, 136);
						break;
					case 135:
						if ((0x4000000040000L & l) != 0L && kind > 33)
							kind = 33;
						break;
					case 136:
						if ((0x200000002L & l) != 0L)
							this.jjCheckNAdd(70);
						break;
					case 137:
						if ((0x1000000010L & l) != 0L)
							this.jjAddStates(133, 138);
						break;
					case 138:
						if ((0x100000001000L & l) != 0L)
							this.jjCheckNAdd(44);
						break;
					case 140:
						if ((0x800000008L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 139;
						break;
					case 142:
						if ((0x800000008L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 141;
						break;
					case 144:
						if ((0x800000008L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 143;
						break;
					case 146:
						if ((0x800000008L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 145;
						break;
					case 148:
						if ((0x200000002000L & l) != 0L)
							this.jjCheckNAddTwoStates(152, 149);
						break;
					case 150:
						if ((0x200000002L & l) != 0L)
							this.jjCheckNAdd(149);
						break;
					case 151:
						if ((0x10000000100000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 150;
						break;
					case 152:
						if ((0x2000000020L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 151;
						break;
					case 153:
						if ((0x800000008L & l) != 0L)
							this.jjCheckNAddStates(139, 142);
						break;
					case 155:
						if ((0x100000001000L & l) != 0L)
							this.jjCheckNAdd(154);
						break;
					case 156:
						if ((0x800000008000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 155;
						break;
					case 157:
						if ((0x4000000040000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 156;
						break;
					case 158:
						if ((0x10000000100000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 157;
						break;
					case 159:
						if ((0x400000004000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 158;
						break;
					case 160:
						if ((0x800000008000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 159;
						break;
					case 161:
						if (this.curChar == 92)
							this.jjCheckNAddStates(62, 65);
						break;
					case 162:
						if (this.curChar == 92)
							this.jjCheckNAdd(163);
						break;
					case 163:
						if ((0x7fffffffffffffffL & l) != 0L && kind > 34)
							kind = 34;
						break;
					case 164:
						if ((0x200000002000L & l) != 0L)
							this.jjCheckNAddTwoStates(168, 165);
						break;
					case 166:
						if ((0x200000002L & l) != 0L)
							this.jjCheckNAdd(165);
						break;
					case 167:
						if ((0x10000000100000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 166;
						break;
					case 168:
						if ((0x2000000020L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 167;
						break;
					case 169:
						if ((0x800000008L & l) != 0L)
							this.jjCheckNAddTwoStates(176, 170);
						break;
					case 171:
						if ((0x100000001000L & l) != 0L)
							this.jjCheckNAdd(170);
						break;
					case 172:
						if ((0x800000008000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 171;
						break;
					case 173:
						if ((0x4000000040000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 172;
						break;
					case 174:
						if ((0x10000000100000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 173;
						break;
					case 175:
						if ((0x400000004000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 174;
						break;
					case 176:
						if ((0x800000008000L & l) != 0L)
							this.jjstateSet[this.jjnewStateCnt++] = 175;
						break;
					default:
						break;
					}
				while (i != startsAt);
			} else {
				int i2 = (this.curChar & 0xff) >> 6;
				long l2 = 1L << (this.curChar & 077);
				MatchLoop: do
					switch (this.jjstateSet[--i]) {
					case 178:
					case 12:
					case 14:
						if ((SubLParserTokenManager.jjbitVec0[i2] & l2) != 0L)
							this.jjCheckNAddStates(0, 2);
						break;
					default:
						break;
					}
				while (i != startsAt);
			}
			if (kind != 0x7fffffff) {
				this.jjmatchedKind = kind;
				this.jjmatchedPos = curPos;
				kind = 0x7fffffff;
			}
			++curPos;
			if ((i = this.jjnewStateCnt) == (startsAt = 177 - (this.jjnewStateCnt = startsAt)))
				return curPos;
			try {
				this.curChar = this.input_stream.readChar();
			} catch (java.io.IOException e) {
				return curPos;
			}
		}
	}

	private int jjMoveNfa_1(int startState, int curPos) {
		int[] nextStates;
		int startsAt = 0;
		this.jjnewStateCnt = 3;
		int i = 1;
		this.jjstateSet[0] = startState;
		int j, kind = 0x7fffffff;
		for (;;) {
			if (++this.jjround == 0x7fffffff)
				this.ReInitRounds();
			if (this.curChar < 64) {
				long l = 1L << this.curChar;
				MatchLoop: do
					switch (this.jjstateSet[--i]) {
					case 0:
						if ((0x2400L & l) != 0L)
							if (kind > 22)
								kind = 22;
						if (this.curChar == 13)
							this.jjstateSet[this.jjnewStateCnt++] = 1;
						break;
					case 1:
						if (this.curChar == 10 && kind > 22)
							kind = 22;
						break;
					case 2:
						if (this.curChar == 13)
							this.jjstateSet[this.jjnewStateCnt++] = 1;
						break;
					default:
						break;
					}
				while (i != startsAt);
			} else if (this.curChar < 128) {
				long l = 1L << (this.curChar & 077);
				MatchLoop: do
					switch (this.jjstateSet[--i]) {
					default:
						break;
					}
				while (i != startsAt);
			} else {
				int i2 = (this.curChar & 0xff) >> 6;
				long l2 = 1L << (this.curChar & 077);
				MatchLoop: do
					switch (this.jjstateSet[--i]) {
					default:
						break;
					}
				while (i != startsAt);
			}
			if (kind != 0x7fffffff) {
				this.jjmatchedKind = kind;
				this.jjmatchedPos = curPos;
				kind = 0x7fffffff;
			}
			++curPos;
			if ((i = this.jjnewStateCnt) == (startsAt = 3 - (this.jjnewStateCnt = startsAt)))
				return curPos;
			try {
				this.curChar = this.input_stream.readChar();
			} catch (java.io.IOException e) {
				return curPos;
			}
		}
	}

	private int jjMoveStringLiteralDfa0_0() {
		switch (this.curChar) {
		case 34:
			return this.jjStartNfaWithStates_0(0, 12, 177);
		case 35:
			return this.jjMoveStringLiteralDfa1_0(0x21e060L);
		case 39:
			return this.jjStopAtPos(0, 7);
		case 40:
			return this.jjStopAtPos(0, 1);
		case 41:
			return this.jjStopAtPos(0, 2);
		case 44:
			this.jjmatchedKind = 10;
			return this.jjMoveStringLiteralDfa1_0(0x200L);
		case 46:
			return this.jjStartNfaWithStates_0(0, 11, 179);
		case 58:
			return this.jjStopAtPos(0, 3);
		case 59:
			return this.jjStopAtPos(0, 20);
		case 96:
			return this.jjStopAtPos(0, 8);
		case 124:
			return this.jjStartNfaWithStates_0(0, 4, 178);
		default:
			return this.jjMoveNfa_0(0, 0);
		}
	}

	private int jjMoveStringLiteralDfa0_1() {
		return this.jjMoveNfa_1(0, 0);
	}

	private int jjMoveStringLiteralDfa0_2() {
		switch (this.curChar) {
		case 124:
			return this.jjMoveStringLiteralDfa1_2(0x800000L);
		default:
			return 1;
		}
	}

	private int jjMoveStringLiteralDfa1_0(long active0) {
		try {
			this.curChar = this.input_stream.readChar();
		} catch (java.io.IOException e) {
			this.jjStopStringLiteralDfa_0(0, active0);
			return 1;
		}
		switch (this.curChar) {
		case 39:
			if ((active0 & 0x40L) != 0L)
				return this.jjStopAtPos(1, 6);
			break;
		case 40:
			if ((active0 & 0x20L) != 0L)
				return this.jjStopAtPos(1, 5);
			break;
		case 43:
			if ((active0 & 0x8000L) != 0L)
				return this.jjStopAtPos(1, 15);
			break;
		case 45:
			if ((active0 & 0x10000L) != 0L)
				return this.jjStopAtPos(1, 16);
			break;
		case 46:
			if ((active0 & 0x4000L) != 0L)
				return this.jjStopAtPos(1, 14);
			break;
		case 58:
			if ((active0 & 0x2000L) != 0L)
				return this.jjStopAtPos(1, 13);
			break;
		case 64:
			if ((active0 & 0x200L) != 0L)
				return this.jjStopAtPos(1, 9);
			break;
		case 124:
			if ((active0 & 0x200000L) != 0L)
				return this.jjStopAtPos(1, 21);
			break;
		default:
			break;
		}
		return this.jjStartNfa_0(0, active0);
	}

	private int jjMoveStringLiteralDfa1_2(long active0) {
		try {
			this.curChar = this.input_stream.readChar();
		} catch (java.io.IOException e) {
			return 1;
		}
		switch (this.curChar) {
		case 35:
			if ((active0 & 0x800000L) != 0L)
				return this.jjStopAtPos(1, 23);
			break;
		default:
			return 2;
		}
		return 2;
	}

	private int jjStartNfa_0(int pos, long active0) {
		return this.jjMoveNfa_0(this.jjStopStringLiteralDfa_0(pos, active0), pos + 1);
	}

	private int jjStartNfaWithStates_0(int pos, int kind, int state) {
		this.jjmatchedKind = kind;
		this.jjmatchedPos = pos;
		try {
			this.curChar = this.input_stream.readChar();
		} catch (java.io.IOException e) {
			return pos + 1;
		}
		return this.jjMoveNfa_0(state, pos + 1);
	}

	private int jjStopAtPos(int pos, int kind) {
		this.jjmatchedKind = kind;
		this.jjmatchedPos = pos;
		return pos + 1;
	}

	private int jjStopStringLiteralDfa_0(int pos, long active0) {
		switch (pos) {
		case 0:
			if ((active0 & 0x1000L) != 0L)
				return 177;
			if ((active0 & 0x10L) != 0L)
				return 178;
			if ((active0 & 0x800L) != 0L)
				return 179;
			if ((active0 & 0x21e060L) != 0L)
				return 31;
			return -1;
		default:
			return -1;
		}
	}

	public void ReInit(ASCII_CharStream stream) {
		this.jjmatchedPos = this.jjnewStateCnt = 0;
		this.curLexState = this.defaultLexState;
		this.input_stream = stream;
		this.ReInitRounds();
	}

	public void ReInit(ASCII_CharStream stream, int lexState) {
		this.ReInit(stream);
		this.SwitchTo(lexState);
	}

	private void ReInitRounds() {
		int i;
		this.jjround = 0x80000001;
		for (i = 177; i-- > 0;)
			this.jjrounds[i] = 0x80000000;
	}

	final void SkipLexicalActions(Token matchedToken) {
		switch (this.jjmatchedKind) {
		default:
			break;
		}
	}

	public void SwitchTo(int lexState) {
		if (lexState >= 3 || lexState < 0)
			throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.",
					TokenMgrError.INVALID_LEXICAL_STATE);
		else
			this.curLexState = lexState;
	}
}
