<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="WS-ResourceProperties" targetNamespace="http://docs.oasis-open.org/wsrf/rpw-2/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://docs.oasis-open.org/wsrf/rpw-2/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://docs.oasis-open.org/wsrf/rpw-2/bindings" location="WS-ResourceProperties_bindings.wsdl"/>
  <wsdl:service name="WS-ResourcePropertiesService">
    <wsdl:port name="GetResourcePropertyDocumentPort" binding="binding:GetResourcePropertyDocumentSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="PutResourcePropertyDocumentPort" binding="binding:PutResourcePropertyDocumentSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="GetResourcePropertyPort" binding="binding:GetResourcePropertySOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="SetResourcePropertiesPort" binding="binding:SetResourcePropertiesSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="InsertResourcePropertiesPort" binding="binding:InsertResourcePropertiesSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="GetMultipleResourcePropertiesPort" binding="binding:GetMultipleResourcePropertiesSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="DeleteResourcePropertiesPort" binding="binding:DeleteResourcePropertiesSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="QueryResourcePropertiesPort" binding="binding:QueryResourcePropertiesSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="UpdateResourcePropertiesPort" binding="binding:UpdateResourcePropertiesSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
