<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TestAuthz" targetNamespace="http://www.globus.org/gram/authz/test/service" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:binding="http://www.globus.org/gram/authz/test/bindings" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://www.globus.org/gram/authz/test/bindings" location="authz_test_bindings.wsdl"/>
  <wsdl:service name="TestAuthzService">
    <wsdl:port name="TestAuthzPortTypePort" binding="binding:TestAuthzPortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
