
package eu.larkc.plugin.reason.esareasoner.esa_ri.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "CorruptIndexException", targetNamespace = "http://webservice.esa_ri.reason.plugins.larkc.eu/")
public class CorruptIndexException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CorruptIndexException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public CorruptIndexException_Exception(String message, CorruptIndexException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public CorruptIndexException_Exception(String message, CorruptIndexException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.CorruptIndexException
     */
    public CorruptIndexException getFaultInfo() {
        return faultInfo;
    }

}
