
package eu.larkc.plugin.reason.esareasoner.esa_ri.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EsaRiWebService", targetNamespace = "http://webservice.esa_ri.reason.plugins.larkc.eu/")
@XmlSeeAlso({
    eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface EsaRiWebService {


    /**
     * 
     * @param radioNrOfResults
     * @param radio
     * @param tokens
     * @return
     *     returns java.lang.String
     * @throws ParseException_Exception
     * @throws IOException_Exception
     * @throws CorruptIndexException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createRDF", targetNamespace = "http://webservice.esa_ri.reason.plugins.larkc.eu/", className = "eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.CreateRDF")
    @ResponseWrapper(localName = "createRDFResponse", targetNamespace = "http://webservice.esa_ri.reason.plugins.larkc.eu/", className = "eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.CreateRDFResponse")
    public String createRDF(
        @WebParam(name = "tokens", targetNamespace = "")
        String tokens,
        @WebParam(name = "radio", targetNamespace = "")
        String radio,
        @WebParam(name = "radioNrOfResults", targetNamespace = "")
        int radioNrOfResults)
        throws CorruptIndexException_Exception, IOException_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.HashMap
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNearestNeigbhoursForESA", targetNamespace = "http://webservice.esa_ri.reason.plugins.larkc.eu/", className = "eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.GetNearestNeigbhoursForESA")
    @ResponseWrapper(localName = "getNearestNeigbhoursForESAResponse", targetNamespace = "http://webservice.esa_ri.reason.plugins.larkc.eu/", className = "eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.GetNearestNeigbhoursForESAResponse")
    public HashMap getNearestNeigbhoursForESA(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws IOException_Exception
    ;

    /**
     * 
     * @param tokens
     * @return
     *     returns java.util.List<net.java.dev.jaxb.array.StringArray>
     * @throws ParseException_Exception
     * @throws IOException_Exception
     * @throws CorruptIndexException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResultsUsingEsa", targetNamespace = "http://webservice.esa_ri.reason.plugins.larkc.eu/", className = "eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.GetResultsUsingEsa")
    @ResponseWrapper(localName = "getResultsUsingEsaResponse", targetNamespace = "http://webservice.esa_ri.reason.plugins.larkc.eu/", className = "eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.GetResultsUsingEsaResponse")
    public List<StringArray> getResultsUsingEsa(
        @WebParam(name = "tokens", targetNamespace = "")
        String tokens)
        throws CorruptIndexException_Exception, IOException_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param tokens
     * @return
     *     returns java.util.List<net.java.dev.jaxb.array.StringArray>
     * @throws ParseException_Exception
     * @throws IOException_Exception
     * @throws CorruptIndexException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResultsUsingRandomIndexing", targetNamespace = "http://webservice.esa_ri.reason.plugins.larkc.eu/", className = "eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.GetResultsUsingRandomIndexing")
    @ResponseWrapper(localName = "getResultsUsingRandomIndexingResponse", targetNamespace = "http://webservice.esa_ri.reason.plugins.larkc.eu/", className = "eu.larkc.plugin.reason.esareasoner.esa_ri.webservice.GetResultsUsingRandomIndexingResponse")
    public List<StringArray> getResultsUsingRandomIndexing(
        @WebParam(name = "tokens", targetNamespace = "")
        String tokens)
        throws CorruptIndexException_Exception, IOException_Exception, ParseException_Exception
    ;

}
