 ; (declare (genprefix smass))

;;;################################################################
;;;
;;;            SMASS  -  semantic access functions
;;;
;;;################################################################

(DEFUN ACTION?  (X)
      ;;THE WORKING PART OF AN ANSWER -- TELLS WHAT TO DO IF THE
      ;;ANSWER IS THE ONE TO BE GIVEN.  MIGHT INCLUDE ACTIONS ON THE
      ;;DISPLAY, AS WELL AS THINGS TO BE PRINTED AND VARIABLES TO BE
      ;;SET, ETC.  THE WHOLE THING IS EVAL-LISTED.
      (G3T X 'ACTION=))

(DEFUN AMBIGUITIES?  (X)
      ;;LIST OF POSSIBLE AMBIGUITIES FOR A SEMANTIC STRUCTURE
      (G3T X 'AMBIGUITIES=))

(DEFUN AND?  (X)
      ;;FIND THE CONJUNCTION LIST OF A CONJOINED SEMANTIC STRUCTURE
      ;;NIL IF THERE IS NONE
      (G3T X 'AND=))

(DEFUN ANSRSS?  (X)
      ;;THE RSS CORRESPONDING TO AN ANSWER NODE (A PROPERTY OF THE
      ;;ANSNODE)
      (G3T X 'ANSRSS=))

(DEFUN DETERMINER?  (X)

;;;     ACCESS FUNCTION. GETS DET OF AN OSS.
      (G3T X 'DETERMINER=))

(DEFUN END?  (TSS-E)
      ;;END TIME FOR TSS
      (G3T TSS-E 'END=))

(DEFUN MARKERS?   (%SENSE)
      ;; ACCESS FUNCTION USED TO GET MARKERS FROM OSS OR RSS
      (G3T %SENSE 'MARKERS=))

(DEFUN MODIFIERS?  (%XSS)
      ;; ACCESS FUNCTION FOR GETTING THE PLANNER CODE SCHEMA OF AN
      ;;OSS OR RSS
      (G3T %XSS 'MODIFIERS=))

(DEFUN NEGATIVE?  (%XSS)

;;; ACCESS FUNCTION FOR OSS
      (G3T %XSS 'NEGATIVE=))

(DEFUN NUMBER?  (OSS)
      ;; GETS THE NUMBER FIELD OF AN OSS
      (CAR (G3T OSS 'DETERMINER=)))

(DEFUN OR?  (X)
      ;;ACCESS FOR LIST OF CONSTITUENTS IN DISJOINED SEMANTIC
      ;;STRUCTURE NIL IF IT ISNT
      (G3T X 'OR=))

(DEFUN OSS?  (X)
      ;;CHECKS TO SEE IF X IS AN OSS
      (G3T X 'OSSNODE=))

(DEFUN PARENT? (NODE) (GETR 'PARENT NODE))

(DEFUN PARSENODE? (X) (G3T X 'PARSENODE=))

;;THE PARSE NODE ASSOCIATED WITH THE SEMANTIC STRUCTURE

(DEFUN PLAUSIBILITY?  (%XSS)
      ;; ACCESS FUNCTION FOR GETTING PLAUSIBILITY OF AN OSS OR RSS
      (OR (G3T %XSS 'PLAUSIBILITY=) 0.))

(DEFUN PLNRCODE? (X) (G3T X 'PLNRCODE=))

;;THE PLANNERCODE GENERATED WHEN AN OBJECT IS ACTUALLY LOOKED FOR IN THE DATA BASE.  IT IS NOT USED AGAIN,
;;BUT IS LEFT SITTING AROUND FOR PEOPLE TO LOOK AT.

(DEFUN QTYPE? (X) (CADDR (G3T X 'DETERMINER=)))

;;QUESTION TYPE FOR QUESTION OSS

(DEFUN QUANTIFIER?  (OSS)
      ;; GETS THE DETERMINER FIELD OF AN OSS
      (CADR (G3T OSS 'DETERMINER=)))

(DEFUN REFER?  (%XSS)
      ;;ACCESS FUNCTION FOR REFER OF OSS OR RSS
      (G3T %XSS 'REFER=))

(DEFUN REL? (X) (G3T X 'REL=))

;;THE OBJECT TO WHICH THIS DESCRIPTION IS TO BE RELATED.

(DEFUN RELATIONS?  (X)
      ;; THE MATERIAL THAT WILL BECOME PLANNER CODE
      (G3T X 'RELATIONS=))

(DEFUN RELMARKERS?  (X)
      ;;MARKERS HELD BY A RELATIVE CLAUSE PRODUCED BY ITS SELECTION
      ;;RESTRICTIONS, TO BE ATTACHED TO THE OBJECT DESCRIPTION
      (G3T X 'RELMARKERS=))

(DEFUN RSS?  (X)
      ;;CHECKS TO SEE IF X IS AN RSS
      (G3T X 'RSSNODE=))

(DEFUN RSSVAR?  (X)
      ;;A VARIABLE OF THE TYPE USED FOR RSS'S -- I.E.  EVX3, ETC.
      (G3T X 'RSSVAR))

(DEFUN START?  (TSS-S)
      ;;START TIME FOR TSS
      (G3T TSS-S 'START=))

(DEFUN SYSTEMS?   (%SENSE)
      ;; ACCESS FUNCTION FOR GETTING THE SYSTEMS OF AN OSS OR RSS
      (G3T %SENSE 'SYSTEMS=))

(DEFUN TENSE?  (X)
      ;;FOR A TSS
      (G3T X 'TENSE=))

(DEFUN TSS? (X) (G3T X 'TSSNODE=))

;;ASSOCIATED WITH EVERY TIME SEMANTIC STRUCTURE.

(DEFUN VARIABLE?
      ;; ACCESS FUNCTION FOR GETTING THE VARIABLE NAME ASSOCIATED WITH AN
      ;;OSS OR RSS
      (X)
      (G3T X 'VARIABLE=))

(DEFUN SMSET (X) (SETR 'SEMANTICS X C) (SETQ SM X))
#|�Visual LISP� Format Options�
(200 6 1 0 T "end of " 100 20 0 0 1 T T nil T)
;*** DO NOT add text below the comment! ***|#
