<wsdl:description>
	<!-- COMMON TO ALL REASONERS -->
	<wsdl:interface name="reasoner"
		sawsdl:modelReference="http://larkc.eu/plugin#Reasoner">
	</wsdl:interface>
	
	<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />

	<!-- SPECIFIC TO THIS IDENTIFIER -->
    <wsdl:service name="urn:eu.larkc.plugin.reason.DIGReasoner" interface="reasoner"
  	sawsdl:modelReference="http://larkc.eu/plugin/reason#DIGReasoner" >
	    <wsdl:endpoint location="java:eu.larkc.plugin.reason.DIGReasoner" />
    </wsdl:service>
</wsdl:description>