/* $Id: WorkerListener.java 150301 2014-04-07 05:15:42Z nwinant $
 */

package com.cyc.base.conn;

//// EXTERNAL IMPORTS
import java.util.EventListener; 

/** *  <P> This interface is one that must be implemented by anyone
 * wishing to listen in on events generated by a SubLWorker.
 *
 * @see SubLWorker
 * @author tbrussea
 * @version $Id: WorkerListener.java 150301 2014-04-07 05:15:42Z nwinant $
 */
public interface WorkerListener extends EventListener {

  /** This event is fired when a SubLWorker is starting the 
   * processing of a SubL task.
   * @param event the event object with details about this event
   */    
  public void notifySubLWorkerStarted(WorkerEvent event);

  /** This event is fired when new data becomes available in 
   * the processing of a SubL task.
   * @param event the event object with details about this event
   */
  public void notifySubLWorkerDataAvailable(WorkerEvent event);

  /** This event is fired when a SubL task has been terminated
   * for any reason.
   * @param event the event object with details about this event
   */
  public void notifySubLWorkerTerminated(WorkerEvent event);

}
