<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="WS-ResourceLifetime" targetNamespace="http://docs.oasis-open.org/wsrf/rlw-2/bindings" xmlns:porttype="http://docs.oasis-open.org/wsrf/rlw-2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://docs.oasis-open.org/wsrf/rlw-2" location="rlw-2.wsdl"/>
  <wsdl:binding name="ImmediateResourceTerminationSOAPBinding" type="porttype:ImmediateResourceTermination">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Destroy">
      <soap:operation soapAction="http://docs.oasis-open.org/wsrf/rlw-2/ImmediateResourceTermination/DestroyRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceNotDestroyedFault">
        <soap:fault name="ResourceNotDestroyedFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnavailableFault">
        <soap:fault name="ResourceUnavailableFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ScheduledResourceTerminationSOAPBinding" type="porttype:ScheduledResourceTermination">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="SetTerminationTime">
      <soap:operation soapAction="http://docs.oasis-open.org/wsrf/rlw-2/ScheduledResourceTermination/SetTerminationTimeRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="UnableToSetTerminationTimeFault">
        <soap:fault name="UnableToSetTerminationTimeFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnavailableFault">
        <soap:fault name="ResourceUnavailableFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TerminationTimeChangeRejectedFault">
        <soap:fault name="TerminationTimeChangeRejectedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
